import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Philosophy' year='c. 375 BCE' title='The Republic' creator='Plato' order='G' orderName='Generative consciousness · explanatory relocation' cms={890} range='Observed across repeated evaluations' headline='Justice stops being a list of right acts and becomes an architecture.' analysis={['The dialogue begins among familiar candidates for justice: repayment, loyalty, reputation, advantage, conventional conduct. Plato’s city–soul construction changes the kind of answer the inquiry can accept. Justice becomes an ordering relation among differentiated functions rather than a catalogue of externally correct behaviors.','That structure then generates consequences. Education, appetite, reason, political form, degeneration and character become intelligible through relations established by the same architecture. The city is therefore not merely an analogy placed beside the person; it is part of a mechanism for discovering what justice would have to be.','The construction is speculative, but it is not unconstrained stipulation. Objections, rival definitions, psychological consequences and political degeneration repeatedly force the proposed structure to carry explanatory weight beyond the point at which it was introduced.']} dimensions={[
{key:'RL',name:'Relational Load',score:'8.91',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'9.28',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'8.59',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'8.89',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'9.09',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'8.83',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why G, not Level 3—or GΩ?' boundary={['Level 3 is too low because the dialogue does not merely make orientation toward justice recursively problematic. It replaces the basis on which justice is explained and uses the replacement to generate further structure.','GΩ is too high. The Republic is historically unavoidable, but historical centrality is not successor-baseline necessity. Adequate political or moral philosophy can reject Plato’s particular city–soul mechanism without thereby becoming structurally inadequate.']} exceptionalTitle='The city is a thinking instrument before it is a political proposal.' exceptional={['Read only as a blueprint for government, the work can look like a sequence of extreme prescriptions. TORC sees the deeper operation in what the construction allows Plato to explain: a property sought in persons is enlarged, differentiated and then returned to the person as structure.','That explanatory reversal is what makes the artifact generative. The famous doctrines matter, but the cognitive achievement lies in the architecture that makes them mutually productive.']} />}
