import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Philosophy' year='1921' title='Tractatus Logico-Philosophicus' creator='Ludwig Wittgenstein' order='G' orderName='Generative consciousness · explanatory relocation' cms={917} range='Observed across repeated evaluations' headline='Many philosophical problems disappear when the conditions of saying them are changed.' analysis={['The Tractatus does not approach philosophy as a warehouse of propositions waiting for better answers. It asks what makes a proposition capable of representing a possible fact at all, and uses logical form, picturing and truth-functional structure to reorganize the relation among language, thought and world.','That changes the explanatory basis of philosophical perplexity. Some apparent problems are no longer treated as difficult questions about hidden objects; they become failures to respect the conditions under which meaningful representation is possible. The work therefore attempts to explain why philosophy generates pseudo-problems, not merely how to answer them.','Its numbered architecture is part of the operation. World, fact, picture, proposition, logic, value and the limits of saying are compressed into a structure in which later claims repeatedly alter the status of earlier ones.']} dimensions={[
{key:'RL',name:'Relational Load',score:'8.34',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'9.71',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'9.14',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'9.18',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'9.68',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'8.66',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why G, not 3c—or GΩ?' boundary={['3c is insufficient because the governing achievement is not an integrated orientation toward a preserved fracture in consciousness. The work proposes a replacement account of why a whole class of philosophical problems arises.','GΩ would require the specific relocation to become an unavoidable baseline constraint on adequate successor inquiry. Wittgenstein’s later work and subsequent philosophy can reject major parts of the picture-theoretic architecture while remaining fully adequate. The artifact changes the explanatory landscape without becoming its permanent mandatory foundation.']} exceptionalTitle='The book tries to change philosophy by changing what can count as a philosophical problem.' exceptional={['That ambition explains the unusual combination of extreme abstraction and compression. A very small vocabulary is made to carry an enormous philosophical field.','Its G status does not depend on whether every Tractarian doctrine survived. A generative explanation can later be rejected and still have genuinely relocated the explanatory basis of its target when the artifact was completed.']} />}
