import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Mathematics' year='1931' title='Incompleteness Theorems' creator='Kurt Gödel' order='GΩ' orderName='Generative consciousness · successor-baseline necessity' cms={960} range='Observed across repeated evaluations' headline='A formal system becomes capable of expressing the limit of what it can formally settle.' analysis={['Gödel’s construction relocates a foundational question. Completeness is no longer only something a mathematician asks from outside a formal system; through arithmetization, statements about syntax and provability can be represented within arithmetic itself.','The resulting limit is not philosophical decoration. It is produced by a proof architecture whose steps are constrained by formal legality, representability, recursion and derivability. The mechanism explains why sufficiently expressive systems encounter propositions whose status cannot be captured by the hoped-for complete effective procedure.','This is an unusually clean G case because the explanatory target and the constraint are almost impossible to confuse with stipulation. The artifact changes what formal axiomatic systems can be understood to promise.']} dimensions={[
{key:'RL',name:'Relational Load',score:'8.6',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'9.8',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'9.8',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'10.0',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'9.7',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'9.4',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why GΩ, not G?' boundary={['G establishes the relocation; GΩ asks whether adequate successor inquiry can simply return to the old explanatory landscape. In foundations and mathematical logic, it cannot.','Successor work can strengthen assumptions, change systems, study different logics or refine the exact scope of the theorems. What it cannot adequately do is treat sufficiently expressive formal axiomatization as though Gödelian incompleteness were not a structural constraint that must be reckoned with.']} exceptionalTitle='The proof does not merely close a problem. It permanently changes the admissible shape of the problem.' exceptional={['Gödel’s profile peaks in abstraction, constraint and inferential distance, while relational load is lower than the headline difficulty might suggest. That asymmetry is informative: extreme formal coupling is not the same thing as heterogeneous relational span.','The GΩ classification captures something CMS alone cannot. The work is not only cognitively enormous; it establishes a changed baseline from which successor inquiry must proceed.']} />}
