import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Film' year='2009' title='The White Ribbon' creator='Michael Haneke' order='3a' orderName='Corrective recursive consciousness' cms={798} range='Observed across repeated evaluations' headline='The village does not merely conceal violence. It damages the conditions by which violence could become knowable.' analysis={['The film distributes authority across family, church, school, class and testimony so that no single institution merely commits the wrong. Together they shape what can count as innocence, guilt, evidence and explanation. The mystery is therefore not simply who committed the acts, but what kind of social order has made reliable orientation to them so difficult.','That is the move beyond symbolic diagnosis. The authoritarian world does not sit outside consciousness as an object that can be cleanly decoded; it conditions the very practices by which characters judge, confess, remember and attribute cause. Yet the direction of the fracture remains principally outward: a pathological order forms damaged subjects.','The narrator’s uncertainty matters because it is produced by that order. TORC therefore reads the film as a strong 3a artifact: consciousness discovers that its relation to reality has become fundamentally unreliable, while the source of that unreliability remains principally located in the external moral and institutional world.']} dimensions={[
{key:'RL',name:'Relational Load',score:'8.20',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'7.73',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'8.15',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'7.73',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'8.35',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'7.04',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why 3a, not 3b?' boundary={['The film comes close to 3b because its subjects reproduce the very order that deforms them. But reproduction is not yet self-implication in the stronger sense. The completed artifact still allows the governing pathology to be located principally in the village’s authoritarian structure.','A 3b reading would require the attempt to orient toward reality itself to become constitutively inseparable from the contradiction. Here, the stronger explanation remains that the external order captures and forms consciousness. That is enough for Level 3, but not enough to move the fracture inward.']} exceptionalTitle='The mystery is structural before it is criminal.' exceptional={['Haneke turns withheld information into evidence about a social system. The inability to settle every act is not a missing solution pasted onto a conventional mystery; it is part of the demonstration that the village has corrupted its own means of knowing.','That gives the film unusual cognitive economy: family violence, class hierarchy, sexuality, religion and historical transition converge on the same problem of damaged orientation.']} />}
