import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Literature' year='1922' title='Ulysses' creator='James Joyce' order='3c' orderName='Integrated recursive consciousness' cms={886} range='Observed across repeated evaluations' headline='The novel does not solve the instability of consciousness. It builds a form capable of inhabiting it.' analysis={['Joyce repeatedly changes the medium through which reality can be apprehended. Memory, language, bodily sensation, grief, sexuality, history and social identity do not merely appear as themes; they alter the conditions under which Bloom, Stephen and Molly can make experience intelligible.','That is why formal experimentation alone does not explain the work. The styles are not detachable virtuosity. They expose the instability of representation itself: consciousness is continually mediated by inherited language, private association, public discourse and bodily circumstance.','Yet the completed artifact does not leave that instability as pure fracture. Bloom’s accommodation of contradiction and Molly’s concluding movement hold desire, betrayal, memory, mortality and attachment together without pretending that any of them has been repaired away.']} dimensions={[
{key:'RL',name:'Relational Load',score:'9.4',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'9.1',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'9.0',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'8.8',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'9.0',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'7.6',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why 3c, not 3b—or G?' boundary={['3b is insufficient because the work does more than demonstrate a consciousness trapped inside its own failed orientation. A coherent mode of inhabiting plurality emerges without restoring simple certainty. That preservation of fracture inside a viable higher orientation is the 3c operation.','G is also unnecessary. Ulysses transforms how consciousness is represented, but it does not establish a generative mechanism that relocates the explanation of an independently identifiable external target in the TORC sense. Its governing achievement remains recursive and integrative rather than explanatory replacement.']} exceptionalTitle='One day becomes large enough to contain a civilization without ceasing to be one day.' exceptional={['The magnitude profile is carried by extraordinary relational load: bodies, streets, styles, memories, myths and histories continually alter one another’s meaning.','But the deeper achievement is operational. Joyce makes instability itself inhabitable. The artifact’s coherence does not come from escaping multiplicity; it comes from constructing a consciousness that can contain it.']} />}
