import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Film' year='2009' title='A Serious Man' creator='Joel & Ethan Coen' order='3b' orderName='Fractured recursive consciousness' cms={780.7} range='Observed across repeated evaluations' headline='Every explanation Larry reaches for becomes another event requiring explanation.' analysis={['Larry begins with a world he expects to be interpretable. Physics, religion, professional procedure, moral conduct and expert advice should provide different routes toward stable orientation. Instead, each route returns him to the same problem: events continue to occur, but the framework that would make them intelligible refuses to settle.','That makes the film more than a story about bad luck or an unjust external world. Larry’s demand for explanation is itself caught inside the contradiction. The rabbis do not simply fail to provide information; the act of seeking a final interpretive standpoint becomes part of what the film destabilizes.','The structure therefore turns explanation back upon the explainer. Probability, theology and moral causality coexist without one acquiring the authority to organize the others, and Larry cannot step outside that competition to decide which reality he inhabits.']} dimensions={[
{key:'RL',name:'Relational Load',score:'7.77',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'7.87',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'7.84',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'7.59',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'8.15',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'7.00',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why 3b, not 3a or 3c?' boundary={['3a would allow the fracture to remain principally in a broken external order. A Serious Man does not. The external events are inseparable from Larry’s own need to interpret them, so the problem captures the standpoint from which the problem is being diagnosed.','3c would require an orientation capable of containing that fracture coherently. The ending does the opposite: the medical call and approaching tornado intensify contingency at the moment any stable moral accounting might have seemed possible.']} exceptionalTitle='The film makes interpretation itself dramatically unstable.' exceptional={['Its economy is striking. Family crisis, tenure, money, physics, Judaism and chance are not separate themes; they become competing explanatory systems around one consciousness that cannot make them converge.','The result is a comparatively compact 3b artifact: lower in magnitude than the largest canonical works, but operationally deeper than a symbolic account of misfortune could explain.']} />}
