export type Artifact = {
  slug:string; title:string; creator:string; year:string; domain:string;
  status:'evaluated'|'in-progress';
  torc?:string; cms?:number; rl?:number; ad?:number; cd?:number; id?:number; ic?:number; gr?:number;
  summary?:string; why?:string; whyNot?:string;
};
export const artifacts: Artifact[] = [
  {"slug": "a-serious-man", "title": "A Serious Man", "creator": "Joel Coen & Ethan Coen", "year": "2007", "domain": "Cinema", "status": "evaluated", "torc": "3b", "cms": 800, "rl": 8.2, "ad": 8.2, "cd": 7.9, "id": 7.8, "ic": 8.6, "gr": 7.2, "summary": "A unanimous seven-evaluator classification of fractured recursive consciousness: the screenplay makes the instability of interpretation itself the governing existential problem.", "why": "All seven evaluators independently classify the screenplay at 3b, finding symbolic organization insufficient to explain its recursive pressure on causal, moral, scientific and religious interpretation.", "whyNot": "The principal upper-boundary question is 3c: gestures toward accepting uncertainty never become a coherent existential orientation capable of integrating the fracture."},
  {"slug": "there-will-be-blood", "title": "There Will Be Blood", "creator": "Paul Thomas Anderson", "year": "2007", "domain": "Screenplays", "status": "in-progress"},
  {"slug": "the-social-network", "title": "The Social Network", "creator": "David Fincher / Aaron Sorkin", "year": "2010", "domain": "Screenplays", "status": "in-progress"},
  {"slug": "the-white-ribbon", "title": "The White Ribbon", "creator": "Michael Haneke", "year": "2009", "domain": "Screenplays", "status": "in-progress"},
  {"slug": "the-lobster", "title": "The Lobster", "creator": "Yorgos Lanthimos", "year": "2015", "domain": "Screenplays", "status": "in-progress"},
  {"slug": "reservoir-dogs", "title": "Reservoir Dogs", "creator": "Quentin Tarantino", "year": "1992", "domain": "Screenplays", "status": "in-progress"},
  {"slug": "the-art-of-fugue", "title": "The Art of Fugue", "creator": "Johann Sebastian Bach", "year": "c. 1740s", "domain": "Music", "status": "evaluated", "torc": "Level 2", "cms": 845, "rl": 8.7, "ad": 8.4, "cd": 9.1, "id": 8.3, "ic": 8.8, "gr": 7.3, "summary": "A unanimous Level-2 result with exceptional cognitive magnitude: formal-symbolic organization is sufficient, while constraint density and integrative compression are the dominant strengths.", "why": "All seven evaluators identify a globally governing formal-symbolic system in which a compact thematic identity survives and organizes extensive contrapuntal transformation.", "whyNot": "No evaluator finds the consciousness–reality recursion required for Level 3, and artifact-internal musical generativity does not qualify as G-level explanatory relocation."},
  {"slug": "grosse-fuge-op-133", "title": "Grosse Fuge, Op. 133", "creator": "Ludwig van Beethoven", "year": "1825–1826", "domain": "Music", "status": "in-progress"},
  {"slug": "eine-kleine-nachtmusik", "title": "Eine kleine Nachtmusik", "creator": "Wolfgang Amadeus Mozart", "year": "1787", "domain": "Music", "status": "in-progress"},
  {"slug": "the-rite-of-spring", "title": "The Rite of Spring", "creator": "Igor Stravinsky", "year": "1913", "domain": "Music", "status": "in-progress"},
  {"slug": "the-end", "title": "The End", "creator": "The Doors", "year": "1967", "domain": "Music", "status": "evaluated", "torc": "3b", "cms": 718, "rl": 7.1, "ad": 7.7, "cd": 6.7, "id": 6.9, "ic": 7.8, "gr": 6.8, "summary": "A narrow 4–3 consensus for fractured recursive consciousness: the song progressively turns ending, mortality, desire, taboo, violence and dissolution into an unresolved confrontation between consciousness and existence.", "why": "Four of seven evaluators find that the completed musical-dramatic architecture exceeds symbolic organization and structurally confronts an irreducible existential fracture.", "whyNot": "Three evaluators retain Level 2 because the same effects may remain sufficiently explained by an exceptionally powerful symbolic architecture; no evaluator finds the integration required for 3c."},
  {"slug": "shine-on-you-crazy-diamond", "title": "Shine On You Crazy Diamond", "creator": "Pink Floyd", "year": "1975", "domain": "Music", "status": "in-progress"},
  {"slug": "a-day-in-the-life", "title": "A Day in the Life", "creator": "The Beatles", "year": "1967", "domain": "Music", "status": "in-progress"},
  {"slug": "paranoid-android", "title": "Paranoid Android", "creator": "Radiohead", "year": "1997", "domain": "Music", "status": "in-progress"},
  {"slug": "kasparov-vs-topalov-wijk-aan-zee-1999", "title": "Kasparov vs. Topalov — Wijk aan Zee 1999", "creator": "Garry Kasparov / Veselin Topalov", "year": "1999", "domain": "Chess", "status": "in-progress"},
  {"slug": "byrne-vs-fischer-game-of-the-century", "title": "Byrne vs. Fischer — Game of the Century", "creator": "Donald Byrne / Bobby Fischer", "year": "1956", "domain": "Chess", "status": "in-progress"},
  {"slug": "anderssen-vs-kieseritzky-immortal-game", "title": "Anderssen vs. Kieseritzky — Immortal Game", "creator": "Adolf Anderssen / Lionel Kieseritzky", "year": "1851", "domain": "Chess", "status": "in-progress"},
  {"slug": "fountain", "title": "Fountain", "creator": "Marcel Duchamp", "year": "1917", "domain": "Art", "status": "in-progress"},
  {"slug": "guernica", "title": "Guernica", "creator": "Pablo Picasso", "year": "1937", "domain": "Art", "status": "in-progress"},
  {"slug": "black-square", "title": "Black Square", "creator": "Kazimir Malevich", "year": "1915", "domain": "Art", "status": "in-progress"},
  {"slug": "relativity", "title": "Relativity", "creator": "M. C. Escher", "year": "1953", "domain": "Art", "status": "in-progress"},
  {"slug": "433", "title": "4′33″", "creator": "John Cage", "year": "1952", "domain": "Art", "status": "in-progress"},
  {"slug": "jaws", "title": "Jaws", "creator": "Peter Benchley & Carl Gottlieb", "year": "1975", "domain": "Screenplays", "status": "evaluated", "torc": "Level 2", "cms": 635, "rl": 7.1, "ad": 5.2, "cd": 7.4, "id": 6.0, "ic": 7.4, "gr": 5.7, "summary": "A tightly constructed screenplay whose consensus profile is strongest in constraint density and integrative compression, with a contested Level 1/Level 2 boundary resolved 5–2 in favor of Symbolic Consciousness.", "why": "Five of seven evaluators find that the shark/threat architecture globally organizes fear, denial, responsibility, expertise, vulnerability, and control strongly enough that direct representation alone under-describes the screenplay.", "whyNot": "Two evaluators retain Level 1, but no evaluator finds the recursive operation required for Level 3; institutional denial remains subordinate to the symbolic and causal shark architecture."},
  {"slug": "der-ring-des-nibelungen", "title": "Der Ring des Nibelungen", "creator": "Richard Wagner", "year": "1848–1874", "domain": "Music", "status": "evaluated", "torc": "3c", "cms": 857, "rl": 9.2, "ad": 8.7, "cd": 8.8, "id": 8.3, "ic": 9.0, "gr": 7.3, "summary": "A five-to-two consensus for 3c: the completed tetralogy recursively exposes contradictions of power, law, freedom and possession, with the majority finding that Brünnhilde's terminal relinquishment integrates rather than merely terminates the fracture.", "why": "All seven evaluators place the complete four-opera cycle in recursive consciousness. Five find the ending crosses the 3b→3c boundary by incorporating catastrophe, loss and contradiction into a coherent terminal orientation.", "whyNot": "Two evaluators retain 3b because the ending may achieve coherence by abolishing the contradictory order rather than sustaining an orientation that contains it. No evaluator finds G warranted."}
];
export function getArtifact(slug:string){ return artifacts.find(a=>a.slug===slug); }
