export type Artifact={slug:string;title:string;creator:string;year:string;domain:string;status:'evaluated'|'in-progress';torc?:string;cms?:number;rl?:number;ad?:number;cd?:number;id?:number;ic?:number;gr?:number;summary?:string;why?:string;whyNot?:string};
export const artifacts:Artifact[]=[
{slug:'war-and-peace',title:'War and Peace',creator:'Leo Tolstoy',year:'1869',domain:'Literature',status:'evaluated',torc:'G',cms:895,rl:9.6,ad:8.8,cd:8.6,id:8.8,ic:9.2,gr:8.4},
{slug:'the-great-gatsby',title:'The Great Gatsby',creator:'F. Scott Fitzgerald',year:'1925',domain:'Literature',status:'evaluated',torc:'2',cms:762,rl:7.6,ad:7.3,cd:7.8,id:7.0,ic:8.3,gr:6.8},
{slug:'the-white-ribbon',title:'The White Ribbon',creator:'Michael Haneke',year:'2009',domain:'Film',status:'evaluated',torc:'3a',cms:805,rl:8.2,ad:7.6,cd:8.1,id:7.6,ic:8.2,gr:6.9},
{slug:'the-lobster',title:'The Lobster',creator:'Yorgos Lanthimos',year:'2015',domain:'Film',status:'evaluated',torc:'2',cms:761,rl:7.6,ad:7.3,cd:7.8,id:6.9,ic:7.8,gr:6.8},
{slug:'a-mathematical-theory-of-communication',title:'A Mathematical Theory of Communication',creator:'Claude E. Shannon',year:'1948',domain:'Science',status:'evaluated',torc:'GΩ',cms:950,rl:8.8,ad:9.4,cd:9.5,id:9.5,ic:9.7,gr:9.8},
{slug:'ulysses',title:'Ulysses',creator:'James Joyce',year:'1922',domain:'Literature',status:'evaluated',torc:'3c',cms:896,rl:9.5,ad:9.1,cd:9.1,id:8.8,ic:9.1,gr:7.7},
{slug:'the-republic',title:'The Republic',creator:'Plato',year:'c. 375 BCE',domain:'Philosophy',status:'evaluated',torc:'G',cms:887,rl:8.9,ad:9.3,cd:8.6,id:8.9,ic:9.1,gr:8.9},
{slug:'on-formally-undecidable-propositions',title:'Incompleteness Theorems',creator:'Kurt Gödel',year:'1931',domain:'Mathematics',status:'evaluated',torc:'GΩ',cms:960,rl:8.6,ad:9.8,cd:9.8,id:10.0,ic:9.7,gr:9.4},
{slug:'a-serious-man',title:'A Serious Man',creator:'Joel & Ethan Coen',year:'2009',domain:'Film',status:'evaluated',torc:'3b',cms:784,rl:7.8,ad:7.8,cd:7.7,id:7.6,ic:8.1,gr:6.8},
{slug:'tractatus-logico-philosophicus',title:'Tractatus Logico-Philosophicus',creator:'Ludwig Wittgenstein',year:'1921',domain:'Philosophy',status:'evaluated',torc:'G',cms:925,rl:8.3,ad:9.7,cd:9.1,id:9.1,ic:9.8,gr:8.7},
{slug:'das-kapital-volume-i',title:'Das Kapital, Vol. I',creator:'Karl Marx',year:'1867',domain:'Philosophy',status:'evaluated',torc:'G',cms:915,rl:9.4,ad:9.2,cd:8.8,id:9.1,ic:9.3,gr:8.8},
{slug:'synecdoche-new-york',title:'Synecdoche, New York',creator:'Charlie Kaufman',year:'2008',domain:'Film',status:'evaluated',torc:'3b',cms:863,rl:9.1,ad:8.9,cd:8.7,id:8.8,ic:8.6,gr:7.5},
{slug:'2001-a-space-odyssey',title:'2001: A Space Odyssey',creator:'Stanley Kubrick',year:'1968',domain:'Film',status:'evaluated',torc:'2',cms:843,rl:8.4,ad:8.6,cd:8.6,id:8.3,ic:8.8,gr:7.7},
{slug:'job',title:'Job',creator:'Hebrew Bible',year:'Ancient',domain:'Scripture',status:'evaluated',torc:'3c',cms:838,rl:8.7,ad:8.1,cd:8.3,id:8.4,ic:8.8,gr:7.8},
{slug:'pulp-fiction',title:'Pulp Fiction',creator:'Quentin Tarantino',year:'1994',domain:'Film',status:'evaluated',torc:'2',cms:787,rl:8.6,ad:6.9,cd:8.8,id:7.8,ic:8.7,gr:6.4},
{slug:'gospel-of-john',title:'Gospel of John',creator:'New Testament',year:'1st century CE',domain:'Scripture',status:'evaluated',torc:'2',cms:823,rl:8.7,ad:8.2,cd:8.0,id:7.8,ic:8.6,gr:7.8},
{slug:'romans',title:'Romans',creator:'Paul the Apostle',year:'c. 57 CE',domain:'Scripture',status:'evaluated',torc:'G',cms:868,rl:8.9,ad:8.7,cd:8.6,id:8.7,ic:8.9,gr:8.3},
{slug:'mulamadhyamakakarika',title:'Fundamental Verses on the Middle Way',creator:'Nāgārjuna',year:'c. 2nd–3rd century CE',domain:'Philosophy',status:'evaluated',torc:'GΩ',cms:945,rl:9.3,ad:9.8,cd:9.3,id:9.7,ic:9.6,gr:9.1},
{slug:'dependent-arising',title:'Dependent Arising',creator:'Kaccānagotta Sutta · SN 12.15',year:'Early Buddhist canon',domain:'Scripture',status:'evaluated',torc:'G',cms:816,rl:7.2,ad:8.5,cd:7.7,id:8.1,ic:8.8,gr:8.3},
{slug:'copernicus-de-revolutionibus',title:'De revolutionibus',creator:'Nicolaus Copernicus',year:'1543',domain:'Science',status:'evaluated',torc:'GΩ',cms:908,rl:9.0,ad:9.0,cd:9.3,id:9.3,ic:9.2,gr:8.8},
{slug:'no-country-for-old-men',title:'No Country for Old Men',creator:'Joel & Ethan Coen',year:'2007',domain:'Film',status:'evaluated',torc:'3b',cms:765,rl:8.0,ad:7.3,cd:8.2,id:7.4,ic:8.4,gr:6.6},
{slug:'philosophiae-naturalis-principia-mathematica',title:'Principia Mathematica',creator:'Isaac Newton',year:'1687',domain:'Science',status:'evaluated',torc:'GΩ',cms:982,rl:9.7,ad:9.7,cd:9.9,id:9.9,ic:9.9,gr:9.8},
{slug:'die-grundlage-der-allgemeinen-relativitatstheorie',title:'General Relativity',creator:'Albert Einstein',year:'1916',domain:'Science',status:'evaluated',torc:'GΩ',cms:953,rl:8.6,ad:9.8,cd:10.0,id:9.8,ic:9.8,gr:9.2},
{slug:'on-the-origin-of-species',title:'On the Origin of Species',creator:'Charles Darwin',year:'1859',domain:'Science',status:'evaluated',torc:'GΩ',cms:937,rl:9.5,ad:8.9,cd:9.2,id:9.5,ic:9.6,gr:9.5},
{slug:'critique-of-pure-reason',title:'Critique of Pure Reason',creator:'Immanuel Kant',year:'1781 / 1787',domain:'Philosophy',status:'evaluated',torc:'GΩ',cms:950,rl:9.5,ad:10.0,cd:9.4,id:9.6,ic:9.8,gr:8.7},
{slug:'on-the-genealogy-of-morality',title:'On the Genealogy of Morality',creator:'Friedrich Nietzsche',year:'1887',domain:'Philosophy',status:'evaluated',torc:'G',cms:867,rl:8.8,ad:9.1,cd:8.1,id:9.0,ic:9.0,gr:8.0},
{slug:'the-social-network',title:'The Social Network',creator:'David Fincher / Aaron Sorkin',year:'2010',domain:'Film',status:'evaluated',torc:'2',cms:777,rl:8.1,ad:7.2,cd:8.3,id:7.7,ic:8.4,gr:6.8},

{slug:'pale-fire',title:'Pale Fire',creator:'Vladimir Nabokov',year:'1962',domain:'Literature',status:'evaluated',torc:'3b',cms:887},
{slug:'glengarry-glen-ross',title:'Glengarry Glen Ross',creator:'David Mamet',year:'1984',domain:'Literature',status:'evaluated',torc:'2',cms:742},
{slug:'there-will-be-blood',title:'There Will Be Blood',creator:'Paul Thomas Anderson',year:'2007',domain:'Film',status:'evaluated',torc:'2',cms:763},
{slug:'1984',title:'1984',creator:'George Orwell',year:'1949',domain:'Literature',status:'evaluated',torc:'3a',cms:832},
{slug:'the-talented-mr-ripley',title:'The Talented Mr. Ripley',creator:'Patricia Highsmith',year:'1955',domain:'Literature',status:'evaluated',torc:'2',cms:747},
{slug:'the-art-of-self-defense',title:'The Art of Self-Defense',creator:'Riley Stearns',year:'2019',domain:'Film',status:'evaluated',torc:'2',cms:710},
{slug:'discrimination-and-disparities',title:'Discrimination and Disparities',creator:'Thomas Sowell',year:'2018',domain:'Philosophy',status:'evaluated',torc:'G',cms:817},
{slug:'notes-from-underground',title:'Notes from Underground',creator:'Fyodor Dostoevsky',year:'1864',domain:'Literature',status:'evaluated',torc:'3b',cms:807,rl:7.6,ad:8.5,cd:7.6,id:8.5,ic:8.5,gr:7.6},
{slug:'waiting-for-godot',title:'Waiting for Godot',creator:'Samuel Beckett',year:'1953',domain:'Literature',status:'evaluated',torc:'3b',cms:793,rl:7.4,ad:8.1,cd:8.0,id:7.9,ic:8.5,gr:7.5},
{slug:'stalker',title:'Stalker',creator:'Andrei Tarkovsky',year:'1979',domain:'Film',status:'evaluated',torc:'3b',cms:828,rl:8.2,ad:8.6,cd:8.2,id:8.4,ic:8.7,gr:7.7},
{slug:'moby-dick',title:'Moby-Dick',creator:'Herman Melville',year:'1851',domain:'Literature',status:'evaluated',torc:'3c',cms:902,rl:9.3,ad:9.2,cd:8.8,id:8.8,ic:9.3,gr:8.5},
{slug:'parasite',title:'Parasite',creator:'Bong Joon Ho',year:'2019',domain:'Film',status:'evaluated',torc:'2',cms:800,rl:8.4,ad:7.4,cd:8.7,id:7.7,ic:8.7,gr:6.9},
{slug:'everything-everywhere-all-at-once',title:'Everything Everywhere All at Once',creator:'Daniel Kwan & Daniel Scheinert',year:'2022',domain:'Film',status:'evaluated',torc:'3c',cms:855,rl:8.9,ad:8.6,cd:8.7,id:8.2,ic:8.8,gr:7.8},
{slug:'the-structure-of-scientific-revolutions',title:'The Structure of Scientific Revolutions',creator:'Thomas S. Kuhn',year:'1962',domain:'Science',status:'evaluated',torc:'GΩ',cms:910,rl:9.0,ad:9.3,cd:8.8,id:9.2,ic:9.4,gr:9.1},
{slug:'computing-machinery-and-intelligence',title:'Computing Machinery and Intelligence',creator:'Alan Turing',year:'1950',domain:'Science',status:'evaluated',torc:'G',cms:882,rl:8.4,ad:9.0,cd:8.6,id:9.1,ic:8.8,gr:9.0},
{slug:'beloved',title:'Beloved',creator:'Toni Morrison',year:'1987',domain:'Literature',status:'evaluated',torc:'3c',cms:873,rl:9.0,ad:8.8,cd:8.8,id:8.6,ic:9.2,gr:8.1},
{slug:'the-metamorphosis',title:'The Metamorphosis',creator:'Franz Kafka',year:'1915',domain:'Literature',status:'evaluated',torc:'2',cms:760,rl:7.3,ad:7.7,cd:7.8,id:7.3,ic:8.2,gr:7.0},
{slug:'the-godfather',title:'The Godfather',creator:'Francis Ford Coppola',year:'1972',domain:'Film',status:'evaluated',torc:'2',cms:812,rl:8.7,ad:7.3,cd:8.8,id:7.8,ic:8.8,gr:7.1},
{slug:'the-magic-mountain',title:'The Magic Mountain',creator:'Thomas Mann',year:'1924',domain:'Literature',status:'evaluated',torc:'3c',cms:863,rl:9.0,ad:9.0,cd:8.6,id:8.4,ic:9.0,gr:8.0,summary:'A close 3b/3c boundary resolved at 3c.'},
{slug:'thus-spoke-zarathustra',title:'Thus Spoke Zarathustra',creator:'Friedrich Nietzsche',year:'1883–1885',domain:'Philosophy',status:'evaluated',torc:'3c',cms:852,rl:8.6,ad:9.1,cd:7.8,id:8.5,ic:8.8,gr:8.2},
{slug:'the-handmaids-tale',title:'The Handmaid’s Tale',creator:'Margaret Atwood',year:'1985',domain:'Literature',status:'evaluated',torc:'3a',cms:812,rl:8.2,ad:7.9,cd:8.2,id:7.7,ic:8.4,gr:7.8},
{slug:'blade-runner',title:'Blade Runner',creator:'Ridley Scott',year:'1982 / Final Cut 2007',domain:'Film',status:'evaluated',torc:'3b',cms:817,rl:8.2,ad:8.3,cd:8.2,id:8.0,ic:8.6,gr:7.5},
{slug:'the-truman-show',title:'The Truman Show',creator:'Peter Weir',year:'1998',domain:'Film',status:'evaluated',torc:'3a',cms:778,rl:7.8,ad:7.6,cd:8.2,id:7.5,ic:8.2,gr:7.2},
{slug:'the-unbearable-lightness-of-being',title:'The Unbearable Lightness of Being',creator:'Milan Kundera',year:'1984',domain:'Literature',status:'evaluated',torc:'3c',cms:845,rl:8.5,ad:8.8,cd:8.1,id:8.5,ic:8.8,gr:8.0},
{slug:'a-clockwork-orange',title:'A Clockwork Orange',creator:'Stanley Kubrick',year:'1971',domain:'Film',status:'evaluated',torc:'3a',cms:792,rl:7.9,ad:7.8,cd:8.4,id:7.8,ic:8.4,gr:7.4},
{slug:'the-remains-of-the-day',title:'The Remains of the Day',creator:'Kazuo Ishiguro',year:'1989',domain:'Literature',status:'evaluated',torc:'3b',cms:808,rl:7.8,ad:8.1,cd:8.0,id:8.3,ic:8.7,gr:7.3},
{slug:'solaris',title:'Solaris',creator:'Andrei Tarkovsky',year:'1972',domain:'Film',status:'evaluated',torc:'3b',cms:835,rl:8.1,ad:8.8,cd:8.3,id:8.5,ic:8.8,gr:7.8},
{slug:'the-logic-of-scientific-discovery',title:'The Logic of Scientific Discovery',creator:'Karl Popper',year:'1934 / 1959',domain:'Science',status:'evaluated',torc:'GΩ',cms:893,rl:8.2,ad:9.0,cd:9.0,id:9.1,ic:9.2,gr:9.1},
{slug:'being-and-nothingness',title:'Being and Nothingness',creator:'Jean-Paul Sartre',year:'1943',domain:'Philosophy',status:'evaluated',torc:'G',cms:920,rl:9.3,ad:9.7,cd:8.8,id:9.4,ic:9.4,gr:8.6},
{slug:'in-search-of-lost-time',title:'À la recherche du temps perdu',creator:'Marcel Proust',year:'1913–1927',domain:'Literature',status:'evaluated',torc:'3c',cms:913,rl:9.7,ad:9.1,cd:9.1,id:9.2,ic:9.6,gr:8.1},
{slug:'dream-of-the-red-chamber',title:'Dream of the Red Chamber',creator:'Cao Xueqin et al.',year:'18th century',domain:'Literature',status:'evaluated',torc:'3c',cms:853,rl:9.5,ad:8.5,cd:8.7,id:8.2,ic:8.6,gr:7.7},
{slug:'one-hundred-years-of-solitude',title:'One Hundred Years of Solitude',creator:'Gabriel García Márquez',year:'1967',domain:'Literature',status:'evaluated',torc:'3b',cms:887,rl:9.2,ad:8.8,cd:8.7,id:8.6,ic:9.2,gr:8.3},
]
export function getArtifact(slug:string){return artifacts.find(a=>a.slug===slug)}
