export const darwin={
torcDistribution:"GΩ 6/7 · G 1/7",cmsRange:"878–893",torcAgreement:"Moderate",cmsStability:"High",dimensionalStability:"Moderate",
evaluators:[["Evaluator 1","GΩ",893],["Evaluator 2","GΩ",878],["Evaluator 3","G",885],["Evaluator 4","GΩ",890],["Evaluator 5","GΩ",878],["Evaluator 6","GΩ",893],["Evaluator 7","GΩ",890]],
dimensions:[
{key:"RL",name:"Relational Load",score:"9.1",range:"8.8\u20139.1",formalDefinition:"Quantity, heterogeneity, interdependence, and coordination of necessary relations.",definition:"How many meaningful relationships must the artifact maintain and coordinate simultaneously? Not simply how many components it contains, but how many components genuinely influence and constrain one another.",rationale:"The artifact coordinates variation, inheritance, competition, selection, divergence, extinction, taxonomy, morphology, embryology, geology and biogeography as a mutually constraining explanatory network rather than a collection of separate observations."},
{key:"AD",name:"Abstraction Depth",score:"8.8",range:"8.6\u20139.1",formalDefinition:"Controlled distance through abstraction layers while preserving relevant distinctions.",definition:"How far can the artifact move beyond the concrete case toward more general, deeper, or meta-representational structures, while preserving the relevant relationships?",rationale:"The work moves from concrete organismal variation through population processes and branching historical descent to general structures that reinterpret species, affinity and classification while preserving empirical correspondence."},
{key:"CD",name:"Constraint Density",score:"8.7",range:"8.4\u20139.0",formalDefinition:"Density of heterogeneous, interacting, simultaneously binding conditions.",definition:"How many interconnected requirements must a successful construction satisfy simultaneously? How much do those constraints narrow the space of solutions that actually work?",rationale:"The explanatory architecture must simultaneously accommodate adaptation, inheritance, competition, extinction, geographical patterns, geological incompleteness, morphology, embryology and difficult counterexamples, while retaining some flexibility in subsidiary mechanisms."},
{key:"ID",name:"Inferential Distance",score:"9.0",range:"9.0\u20139.1",formalDefinition:"Distance between available premises/conditions and the non-obvious successful solution or relation derived from them.",definition:"How large and non-routine is the reasoning leap from the available information to the successful discovery, solution, or reconstruction?",rationale:"The evaluators converge on an exceptional non-routine reconstruction from dispersed observations to a unified historical-generative mechanism; this is the most numerically stable dimension across the seven reports."},
{key:"IC",name:"Integrative Compression",score:"9.1",range:"9.0\u20139.3",formalDefinition:"How economically a structure coordinates and preserves a substantially larger body of information and relations.",definition:"How much diverse information, complexity, or structure can the artifact organize through a relatively compact underlying architecture, without discarding important distinctions?",rationale:"A comparatively compact architecture of variation, inheritance, differential preservation, divergence, extinction and common descent organizes an unusually large heterogeneous evidential field while preserving distinct biological phenomena."},
{key:"GR",name:"Generalization Reach",score:"8.4",range:"8.2\u20139.0",formalDefinition:"How far the demonstrated structure remains applicable across materially heterogeneous problem-spaces.",definition:"How far can the same underlying structure be transferred to substantially different cases, problems, or domains, while preserving the relevant structural relationships?",rationale:"The structure transfers extremely broadly across organisms, environments, evidence classes and timescales, but most evaluators distinguish that enormous within-biology reach from transfer across genuinely distant problem-spaces."},
]};