export const warAndPeace={
torcDistribution:"3c 6/7 · G 1/7",cmsRange:"807–855",torcAgreement:"High",cmsStability:"High",dimensionalStability:"High",
evaluators:[["Evaluator 1","3c",842],["Evaluator 2","3c",835],["Evaluator 3","3c",838],["Evaluator 4","3c",838],["Evaluator 5","3c",827],["Evaluator 6","3c",807],["Evaluator 7","G",855]],
dimensions:[
{key:"RL",formalDefinition:"Quantity, heterogeneity, interdependence, and coordination of necessary relations.",name:"Relational Load",score:"9.2",definition:"How many meaningful relationships must the artifact maintain and coordinate simultaneously? Not simply how many components it contains, but how many components genuinely influence and constrain one another.",rationale:"The novel coordinates exceptionally consequential relations among individual psychology, families, social systems, military operations, historical events, philosophical claims and long temporal developments."},
{key:"AD",formalDefinition:"Controlled distance through abstraction layers while preserving relevant distinctions.",name:"Abstraction Depth",score:"8.8",definition:"How far can the artifact move beyond the concrete case toward more general, deeper, or meta-representational structures, while preserving the relevant relationships?",rationale:"Concrete experience is repeatedly carried into higher-order structures concerning agency, causation, freedom, necessity, mortality and historical explanation."},
{key:"CD",formalDefinition:"Density of heterogeneous, interacting, simultaneously binding conditions.",name:"Constraint Density",score:"8.3",definition:"How many interconnected requirements must a successful construction satisfy simultaneously? How much do those constraints narrow the space of solutions that actually work?",rationale:"Historical chronology, character development, family structures, military events, social convention, thematic recurrence and philosophical exposition impose dense cross-level requirements, while meaningful local latitude remains."},
{key:"ID",formalDefinition:"Distance between available premises/conditions and the non-obvious successful solution or relation derived from them.",name:"Inferential Distance",score:"8.2",definition:"How large and non-routine is the reasoning leap from the available information to the successful discovery, solution, or reconstruction?",rationale:"The work performs major non-routine restructurings of familiar relations between intention and outcome, individual agency and historical causation, and existential contradiction and viable orientation."},
{key:"IC",formalDefinition:"How economically a structure coordinates and preserves a substantially larger body of information and relations.",name:"Integrative Compression",score:"8.3",definition:"How much diverse information, complexity, or structure can the artifact organize through a relatively compact underlying architecture, without discarding important distinctions?",rationale:"Extraordinary heterogeneity is organized through a recurring family of structures linking agency and necessity, private and historical life, mortality, family, causation and perspective."},
{key:"GR",formalDefinition:"How far the demonstrated structure remains applicable across materially heterogeneous problem-spaces.",name:"Generalization Reach",score:"7.4",definition:"How far can the same underlying structure be transferred to substantially different cases, problems, or domains, while preserving the relevant structural relationships?",rationale:"The architecture transfers strongly across human, psychological, social, institutional, political, existential and historical cases, but less decisively into markedly remote problem-spaces."}
]};