import Link from 'next/link';
import type {ReactNode} from 'react';
import styles from './artifact-analysis.module.css';

type Dim={key:string;name:string;score:string;artifact:string};
type Props={domain:string;year:string;title:ReactNode;creator:string;order:string;orderName:string;cms?:number;range?:string;headline:string;analysis:string[];dimensions?:Dim[];boundaryTitle:string;boundary:string[];exceptionalTitle:string;exceptional:string[]};
const defs:Record<string,[string,string,string]>= {
 RL:['Relational Load','Quantity, heterogeneity, interdependence, and coordination of necessary relations.','How many meaningful relationships must the artifact maintain and coordinate simultaneously? Not simply how many components it contains, but how many components genuinely influence and constrain one another.'],
 AD:['Abstraction Depth','Controlled distance through abstraction layers while preserving relevant distinctions.','How far can the artifact move beyond the concrete case toward more general, deeper, or meta-representational structures, while preserving the relevant relationships?'],
 CD:['Constraint Density','Density of heterogeneous, interacting, simultaneously binding conditions.','How many interconnected requirements must a successful construction satisfy simultaneously? How much do those constraints narrow the space of solutions that actually work?'],
 ID:['Inferential Distance','Distance between available premises/conditions and the non-obvious successful solution or relation derived from them.','How large and non-routine is the reasoning leap from the available information to the successful discovery, solution, or reconstruction?'],
 IC:['Integrative Compression','How economically a structure coordinates and preserves a substantially larger body of information and relations.','How much diverse information, complexity, or structure can the artifact organize through a relatively compact underlying architecture, without discarding important distinctions?'],
 GR:['Generalization Reach','How far the demonstrated structure remains applicable across materially heterogeneous problem-spaces.','How far can the same underlying structure be transferred to substantially different cases, problems, or domains, while preserving the relevant structural relationships?']
};
export default function ArtifactAnalysis(p:Props){return <main className={styles.page}>
<header className={styles.hero}><div className="eyebrow">{p.domain} · {p.year} · TORC analysis</div><h1>{p.title}</h1><p className={styles.creator}>{p.creator}</p><div className={styles.verdictGrid}><div><span>Operational Order</span><strong>{p.order}</strong><small>{p.orderName}</small></div><div><span>Cognitive Magnitude</span><strong>{p.cms ?? '—'}</strong><small>Production CMS</small></div></div></header>
<article className={styles.essay}><section><div className={styles.kicker}>Analysis</div><h2>{p.headline}</h2>{p.analysis.map((x,i)=><p key={i}>{x}</p>)}</section></article>
{p.dimensions?.length ? <section className={styles.cmsSection}><div className={styles.kicker}>Cognitive architecture</div><h2 className={styles.dimensionsTitle}>The six-dimensional model</h2><p className={styles.cmsIntro}>See how TORC’s Cognitive Magnitude Score (CMS) is carried across the artifact.</p><div className={styles.dimensions}>{p.dimensions.map(d=><details className={styles.dimension} key={d.key}><summary><span className={styles.dimKey}>{d.key}</span><span className={styles.dimName}><b>{d.name}</b></span><span className={styles.bar} aria-hidden="true"><span style={{width:`${Number(d.score)*10}%`}} /></span><strong>{d.score}</strong></summary><div className={styles.dimBody}><p><b>Formal definition.</b> {defs[d.key][1]}</p><p><b>In plain language.</b> {defs[d.key][2]}</p><p><b>Why this artifact scores {d.score}.</b> {d.artifact}</p></div></details>)}</div></section> : null}
<article className={`${styles.essay} ${styles.essayAfterDimensions}`}><section className={styles.boundary}><h2>{p.boundaryTitle}</h2>{p.boundary.map((x,i)=><p key={i}>{x}</p>)}<Link className={`${styles.methodologyCta} ${styles.orderModelCta}`} href="/methodology#operational-order"><span>TORC classification model</span><strong>Explore the 7 Operational Orders</strong><span aria-hidden="true">→</span></Link></section></article>
<section className={styles.exceptional}><div className={styles.kicker}>What makes it exceptional</div><h2>{p.exceptionalTitle}</h2>{p.exceptional.map((x,i)=><p key={i}>{x}</p>)}</section>
<section className={styles.bottomCta}><Link className={styles.submitButton} href="/evaluate-your-work">Submit your artifact →</Link><div><span>TORC Development Analysis</span><h2>What is your artifact actually doing?</h2><p>Find the deepest operation already present in the work—and the structural boundary keeping it from becoming fully realized.</p></div></section>
</main>}
