import {magicMountain as m} from '@/lib/magicMountain';
import styles from './methodology.module.css';

const orders = [
 {key:'1',name:'Direct / Functional Cognition',formal:'The artifact performs a direct, bounded cognitive operation without requiring recursive reorientation of consciousness.',plain:'The work solves, organizes, represents or executes something effectively within an accepted frame of reality.'},
 {key:'2',name:'Systemic / Relational Cognition',formal:'The artifact coordinates complex relations, systems or recursive structures while remaining within a stable orientation toward reality.',plain:'The work can be extremely complex, recursive and intelligent without making consciousness itself fundamentally problematic.'},
 {key:'3a',name:'External-Fracture Recursive Consciousness',formal:'A fundamental fracture is organized principally in the world or order outside consciousness.',plain:'Reality itself becomes difficult to orient within: the problem is not merely complexity, but a world whose structure destabilizes ordinary orientation.'},
 {key:'3b',name:'Fractured Consciousness',formal:'The fracture implicates consciousness\'s own attempt to orient itself toward reality.',plain:'The work no longer gives consciousness a secure position outside the problem. The act of seeing, knowing or orienting is itself caught in the fracture.'},
 {key:'3c',name:'Integrated Consciousness',formal:'A self-implicating fracture is integrated into a coherent higher orientation without being erased, repaired away or falsely resolved.',plain:'The work finds a way of inhabiting the fracture. The contradiction remains real, but consciousness can orient through it rather than simply collapse inside it.'},
 {key:'G',name:'Generative Cognition',formal:'The artifact establishes a generative explanation for an independently identifiable target such that lower-order accounts become insufficient.',plain:'The work does not only deepen our experience of a problem. It builds an account of why the thing happens the way it does.'},
 {key:'GΩ',name:'Successor-Generative Cognition',formal:'A G-level explanatory structure is independently taken up, extended or operationalized in successor cognition beyond the originating artifact.',plain:'The artifact does not merely generate an explanation. That explanation becomes capable of producing further independent cognition beyond the work itself.'}
];

export default function Methodology(){return <main>
<header className="page-title"><div className="eyebrow">TORC methodology</div><h1>How the profile is read</h1><p className="lede">TORC evaluates demonstrated cognition in completed artifacts through two coordinates: Operational Order and Cognitive Magnitude. Together they form the Demonstrated Intelligence Profile.</p></header>
<section className="section prose"><h2>Two coordinates</h2><p><b>Operational Order</b> identifies the kind of cognitive operation the completed artifact demonstrably performs.</p><p><b>Cognitive Magnitude</b> measures the scale and architecture of cognition demonstrated in successfully constructing that operation.</p><p>The coordinates answer different questions. A higher magnitude does not mechanically produce a higher Operational Order, and Operational Order is not calculated from the six magnitude dimensions.</p></section>
<section className="section" id="operational-order"><div className="eyebrow">Operational Order</div><h2>The full Operational Order model</h2><p className={styles.intro}>The sequence is categorical, not a ladder of decoration or difficulty. Each order describes a different governing operation of the completed artifact.</p><div className={styles.orderList}>{orders.map(o=><details className={styles.order} key={o.key}><summary><span>{o.key}</span><strong>{o.name}</strong><em>Open definition</em></summary><div><p><b>Formal definition.</b> {o.formal}</p><p><b>In plain language.</b> {o.plain}</p></div></details>)}</div></section>
<section className="section" id="dimensions"><div className="eyebrow">Cognitive Magnitude</div><h2>The six dimensions</h2><p className={styles.intro}>The six dimensions show where an artifact's demonstrated cognitive magnitude is carried. They are lenses on the architecture, not six independent ratings added together by intuition.</p><div className="dimensions">{m.dimensions.map(d=><div className="methodDimension" id={d.key.toLowerCase()} key={d.key}><div className="dimKey">{d.key}</div><div><h3>{d.name}</h3><p className="formalDefinition"><b>Formal definition.</b> {d.formalDefinition}</p><p><b>In plain language.</b> {d.definition}</p></div></div>)}</div></section>
<section className="section prose"><h2>Evaluation transparency</h2><p>TORC conclusions are produced through repeated analytical evaluation and protocol-governed adjudication. Public artifact pages present the final determination, the evidence needed to understand it, and meaningful uncertainty where relevant.</p><p>The complete evaluation protocol, evaluator records, prompts, thresholds and adjudication procedures are proprietary and are not publicly disclosed.</p></section>
</main>}
