import ArtifactAnalysis from '../components/ArtifactAnalysis';

export default function Page(){
  return <ArtifactAnalysis
    domain='Philosophy & Theory'
    year='1781 / 1787'
    title='Critique of Pure Reason'
    creator='Immanuel Kant'
    order='G'
    orderName='Generative'
    cms={944}
    headline='Kant doesn’t simply propose a new theory of knowledge. He changes what a claim has to do before it can count as knowledge in the first place.'
    analysis={['Traditional metaphysical questions appear to concern objects: the soul, the world, causality, God, substance, reality. Kant performs a peculiar reversal. Before reason can legitimately decide what such things are like, it must investigate the conditions under which objects can become available to cognition at all.','That move changes the status of the representational relation.','Sensibility, intuition, concepts, categories, synthesis and apperception are not merely additional things Kant wants us to believe in. Together they help determine the conditions under which representations can possess objective validity. The question is no longer simply whether a representation corresponds to an object. The architecture through which something can stand as an object of possible experience has entered the determination of what legitimate objective cognition is.','The same reconstruction then generates limits. If the conditions that make objective cognition possible apply only within certain bounds, reason cannot simply carry its concepts beyond those bounds and expect them to retain the same standing.','The Critique therefore does not bolt skepticism onto a positive theory of knowledge. Its account of how knowledge becomes possible also produces an account of where knowledge ceases to be legitimately available.','That is why TORC classifies the work as G.']}
    dimensions={[
{key:'RL',name:'Relational Load',score:'9.4',artifact:'The score reflects the artifact-grounded relational load demonstrated in this evaluation.'},
{key:'AD',name:'Abstraction Depth',score:'9.8',artifact:'The score reflects the artifact-grounded abstraction depth demonstrated in this evaluation.'},
{key:'CD',name:'Constraint Density',score:'9.5',artifact:'The score reflects the artifact-grounded constraint density demonstrated in this evaluation.'},
{key:'ID',name:'Inferential Distance',score:'9.6',artifact:'The score reflects the artifact-grounded inferential distance demonstrated in this evaluation.'},
{key:'IC',name:'Integrative Compression',score:'9.4',artifact:'The score reflects the artifact-grounded integrative compression demonstrated in this evaluation.'},
{key:'GR',name:'Generalization Reach',score:'9.0',artifact:'The score reflects the artifact-grounded generalization reach demonstrated in this evaluation.'}
    ]}
    boundaryTitle='Why G, not M3?'
    boundary={['An M3 account already captures something important. Cognition is no longer outside the reality it is trying to understand. The operation of knowing becomes consequential to what can legitimately be known.','But Kant goes further.','The Critique reorganizes the relation by which representations obtain objective standing. The conditions of representation are no longer merely facts about the knowing subject that must be taken into account alongside objects. They participate in determining what can count as an object of possible experience and therefore what kinds of claims can legitimately stand as knowledge.','That produces a successor organization. Mathematics, natural science, ordinary empirical cognition and metaphysical reasoning can now be distinguished according to the conditions under which their claims possess—or fail to possess—objective validity.','G is therefore not awarded because Kant is unusually abstract, influential or revolutionary. His CMS and his Mode are separate judgments.','It is awarded because the governing architecture changes the conditions under which representation can do the explanatory work that philosophy had previously asked it to do.']}
    exceptionalKicker="What TORC reveals"
    exceptionalTitle='Kant’s positive theory and his limits on reason are two sides of the same cognitive architecture.'
    exceptional={['It is easy to describe the Critique as a book that restricts metaphysics. It is equally easy to describe it as a theory of how experience and objective cognition are possible.','TORC shows why those descriptions belong together.','The machinery that explains how representations can acquire objective validity also explains why the same machinery cannot simply be extended without limit. The boundary is generated from inside the architecture rather than imposed afterward.','That gives Kant extraordinary integrative compression. A relatively small family of distinctions coordinates mathematics, causality, experience, self-consciousness, natural science and metaphysical error while preserving important differences among them.','But the G result identifies something that the magnitude score alone cannot: Kant does not merely explore an extraordinarily large space of thought. He reorganizes the conditions under which that space can be cognitively occupied.']}
    evaluationDetails={<><p><b>Evaluative unit:</b> Complete philosophical work</p><p><b>Original language:</b> German</p><p><b>Language evaluated:</b> English</p><p><b>Reference translation:</b> Paul Guyer & Allen W. Wood</p><p><b>Edition:</b> The Cambridge Edition of the Works of Immanuel Kant, Cambridge University Press, 1998</p><p><b>Textual scope:</b> Complete Critique of Pure Reason, preserving the A/B material from Kant’s 1781 and 1787 editions as represented in the Cambridge edition</p><p><b>Version status:</b> Reference translation and edition</p><p><b>Included:</b> Kant’s primary philosophical text, including relevant A/B textual material</p><p><b>Excluded:</b> Editors’ introduction, editorial notes, glossaries, translator/editor commentary, secondary scholarship, reception history, and later Kantian interpretation</p><p><b>Evaluation basis:</b> Primary philosophical artifact</p></>}
  />;
}
