import ArtifactAnalysis from '../components/ArtifactAnalysis';
export default function Page(){return <ArtifactAnalysis domain='Film' year='2015' title='The Lobster' creator='Yorgos Lanthimos' order='2' orderName='Symbolic consciousness' cms={736} range='Observed across repeated evaluations' headline='Its world is absurd because a social metaphor has been made literal with almost no remainder.' analysis={['The hotel, animal transformation, matching traits, the Loners and the punishments do not merely decorate a satire about relationships. They convert the social demand to form a couple into a complete symbolic environment in which intimacy, identity and survival are governed by the same rule.','The film’s intelligence lies in the symmetry of its construction. The hotel makes coupling compulsory; the woods make attachment punishable. David moves between opposed systems that share the same deeper error: both replace relation with rule. The opposition therefore expands the symbolic machine rather than escaping it.','TORC keeps the film at Level 2 because that machine remains sufficient to explain the completed artifact. Its world is pathological, self-reinforcing and capable of trapping its subjects without making consciousness’s orientation toward reality the governing recursive problem.']} dimensions={[
{key:'RL',name:'Relational Load',score:'7.4',artifact:'The score reflects the span and interdependence of the artifact’s necessary relations rather than simple component count.'},
{key:'AD',name:'Abstraction Depth',score:'7.2',artifact:'The score reflects how far the artifact moves through controlled abstraction while preserving the distinctions that matter.'},
{key:'CD',name:'Constraint Density',score:'7.6',artifact:'The score reflects how densely different requirements constrain one another and narrow the viable solution space.'},
{key:'ID',name:'Inferential Distance',score:'6.9',artifact:'The score reflects the non-routine inferential movement required to establish the artifact’s governing relation.'},
{key:'IC',name:'Integrative Compression',score:'7.7',artifact:'The score reflects how economically a smaller architecture organizes a substantially larger field without flattening it.'},
{key:'GR',name:'Generalization Reach',score:'6.7',artifact:'The score reflects structural transfer to materially different problem-spaces, not mere relevance or fame.'}
]} boundaryTitle='Why Level 2, not Level 3?' boundary={['The strongest Level 3 pressure is 3a: an external order is obviously wrong and consciousness must navigate it. But the film preserves a stable satirical position from which both the hotel and the Loners can be diagnosed. Their pathology is the represented object, not a fracture that destroys the adequacy of representation itself.','Even David’s final dilemma remains legible inside the symbolic logic the film has established. The system has entered him, but the artifact does not require a higher recursive operation to explain that capture.']} exceptionalTitle='The conceit is not the achievement. The symmetry is.' exceptional={['Many satires invent one absurd rule. The Lobster builds two opposed regimes and shows that both can instantiate the same coercive architecture. That gives a relatively simple premise unusual integrative power.','Its Level 2 classification is therefore substantive, not dismissive: the film demonstrates how far disciplined symbolic construction can go before recursive fracture becomes necessary.']} />}
